This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./instruction.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file instruction.acn....done (9 entries accepted, 0 rejected).
Sorting entries....done (34 comparisons).
Generating output file instruction.acr....done (24 lines written, 0 warnings).
Output written in instruction.acr.
Transcript written in instruction.alg.
